name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build -t sjmaabane/whatsapp_fastapi_webhook:latest2

    - name: Push the Docker image
      run: docker push sjmaabane/whatsapp_fastapi_webhook:latest2
